test:
#  hostport: httpbin.org:80
#  hostport: localhost:5000
#  uri: http://${test.hostport}
  uri: lb://httpbin


spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      routes:
      - id: websocket_test
        uri: http://www.google.com
        predicates:
        - Path=/echo
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
